<a href="https://colab.research.google.com/github/HanzlaAlvi/Machine-Learning/blob/Tasks/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [185]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy<2,>=1.21 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.10/dist-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [187]:
def codeRead(test):
    return pd.read_csv(test)
test='/content/drive/MyDrive/Machine Learning/Assignment 2/heart.csv'
test=codeRead(test)

In [188]:
!ls /content/drive/MyDrive/Machine\ Learning/Assignment\ 2

'Assignment 2.ipynb'   Assignment2.ipynb   heart.csv

In [189]:
test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140.0,203,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145.0,174,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148.0,203,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138.0,294,1,1,106.0,0,1.9,1,3,2,0

In [190]:
test.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140.0,221,0,1,164.0,1,0.0,2,0,2,1
1021,60,1,0,125.0,258,0,0,141.0,1,2.8,1,1,3,0
1022,47,1,0,110.0,275,0,0,118.0,1,1.0,1,1,2,0
1023,50,0,0,110.0,254,0,0,159.0,0,0.0,2,0,2,1
1024,54,1,0,120.0,188,0,1,113.0,0,1.4,1,1,3,0

In [191]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1024 non-null   float64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1024 non-null   float64
 8   exang     1025 non-null   int64
 9   oldpeak   1024 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(3), int64(11)
memory usage: 112.2 KB

In [192]:
#to check no of rows and no of columns
test.shape

(1025, 14)

In [193]:
test.duplicated()
#here we check out the duplicates in the dataset.

0       False
1       False
2       False
3       False
4       False
        ...
1020     True
1021     True
1022     True
1023     True
1024     True
Length: 1025, dtype: bool

In [194]:
#Here i removed the duplicated in the dataset or to say drop it from dataset
test.drop_duplicates()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140.0,203,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145.0,174,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148.0,203,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138.0,294,1,1,106.0,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120.0,211,0,0,115.0,0,1.5,1,0,2,1
733,44,0,2,108.0,141,0,1,175.0,0,0.6,1,0,2,1
739,52,1,0,128.0,255,0,1,161.0,1,0.0,2,1,3,0
843,59,1,3,160.0,273,0,0,125.0,0,0.0,2,0,2,0
878,54,1,0,120.0,188,0,1,113.0,0,1.4,1,1,3,0

In [195]:
#Here I replace all the question marks (?) with NAN which means not a number to simplify the dataset for ourselves
test.replace('?',np.nan)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1,168.0,0,1.0,2,2,3,0
1,53,1,0,140.0,203,1,0,155.0,1,3.1,0,0,3,0
2,70,1,0,145.0,174,0,1,125.0,1,2.6,0,0,3,0
3,61,1,0,148.0,203,0,1,161.0,0,0.0,2,1,3,0
4,62,0,0,138.0,294,1,1,106.0,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1,164.0,1,0.0,2,0,2,1
1021,60,1,0,125.0,258,0,0,141.0,1,2.8,1,1,3,0
1022,47,1,0,110.0,275,0,0,118.0,1,1.0,1,1,2,0
1023,50,0,0,110.0,254,0,0,159.0,0,0.0,2,0,2,1
1024,54,1,0,120.0,188,0,1,113.0,0,1.4,1,1,3,0

In [234]:
#Here the fillna method replaces all NaN values in the column with the specified value, which in this case is the mean of the column ,so i filled the missing values with 'length' with the mean of 'length' column and I also saved the whole in a variable and print the mean
mean=test['trestbps'].fillna(test['trestbps'].mean())
print(mean)
#Here i Calculated the Median of 'length' from the dataset and printed the median
median=test['trestbps'].median()
print(median)

0     -0.369877
1      0.483853
2      0.768430
3      0.939176
4      0.370023
         ...
299   -0.654454
300   -1.337438
301   -0.199131
302    1.622160
303   -0.654454
Name: trestbps, Length: 304, dtype: float64
-0.08530026680767328

In [196]:
test.isnull().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     0
thalach     1
exang       0
oldpeak     1
slope       0
ca          0
thal        0
target      0
dtype: int64

In [197]:
#to check the columns
test.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [198]:
from sklearn.impute import SimpleImputer

# Create an imputer object with strategy 'mean'
imputer = SimpleImputer(strategy='mean')

# Apply the imputer to your DataFrame
test = pd.DataFrame(imputer.fit_transform(test), columns=test.columns)

In [199]:
test.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [200]:
# Handling missing values (using mean imputation for all columns)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
test = pd.DataFrame(imputer.fit_transform(test), columns=test.columns)

# Handling duplicates
test.drop_duplicates(inplace=True)

# Data type conversion (example for 'sex' column)
test['sex'] = test['sex'].astype('category')

# Feature scaling (using StandardScaler)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numerical_features = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']  # List your numerical features
test[numerical_features] = scaler.fit_transform(test[numerical_features])

# ... (other steps like outlier detection, feature engineering, encoding)

# Data splitting
from sklearn.model_selection import train_test_split
X = test.drop('target', axis=1)  # Features
y = test['target']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Set random_state for reproducibility

In [201]:
#to check the columns
test.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [202]:
#Here i calculated the mean from the dataset For 'length' which is present is one of the columns
test['slope'].mean()

1.394736842105263

In [203]:
#Here the fillna method replaces all NaN values in the column with the specified value, which in this case is the mean of the column ,so i filled the missing values with 'length' with the mean of 'length' column and I also saved the whole in a variable and print the mean
mean=test['slope'].fillna(test['slope'].mean())
print(mean)

0      2.0
1      0.0
2      0.0
3      2.0
4      1.0
      ...
723    1.0
733    1.0
739    2.0
843    2.0
878    1.0
Name: slope, Length: 304, dtype: float64

In [204]:
from sklearn.impute import SimpleImputer
# Create an imputer object with strategy 'mean' to replace NaN values.
imputer = SimpleImputer(strategy='mean')

# Apply the imputer to your DataFrame. This fits the imputer on your data
# and then transforms it by replacing NaN values with the calculated means.
test = pd.DataFrame(imputer.fit_transform(test), columns=test.columns)

In [205]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

Applying KNN model

In [206]:
test.sex

0      1.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
299    0.0
300    0.0
301    1.0
302    1.0
303    1.0
Name: sex, Length: 304, dtype: float64

In [207]:
X= test.iloc[:, :-1].values
y= test.iloc[:, 4].values

In [208]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [209]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train= scaler.transform(X_train)
X_test= scaler.transform(X_test)

In [210]:
!pip install scikit-learn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.neighbors import KNeighborsClassifier

# Assuming 'y' is your continuous target variable
# Initialize KBinsDiscretizer with desired settings
discretizer = KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='uniform')

# Fit and transform the target variable 'y' to discrete values
y_discretized = discretizer.fit_transform(y.reshape(-1, 1)) # Reshape y for single feature
y_discretized = y_discretized.astype(int).ravel() # Convert to integers for classification

# Now use the discretized target in train_test_split:
X_train, X_test, y_train, y_test = train_test_split(X, y_discretized, test_size=0.20)

# Proceed with model training:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

KNeighborsClassifier()

In [211]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [212]:
y_pred = classifier.predict(X_test)

In [213]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.69      0.79        16
           1       0.78      0.97      0.87        37
           2       1.00      0.38      0.55         8

    accuracy                           0.82        61
   macro avg       0.90      0.68      0.73        61
weighted avg       0.85      0.82      0.80        61

[[11  5  0]
 [ 1 36  0]
 [ 0  5  3]]

In [214]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search over
param_grid = {'n_neighbors': range(1, 21)}  # Try values from 1 to 20 for n_neighbors

# Create a GridSearchCV object
grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy')  # Use 5-fold cross-validation and accuracy as the scoring metric

# Fit the grid search to your training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_n_neighbors = grid_search.best_params_['n_neighbors']

# Create a new classifier with the best hyperparameters
best_classifier = KNeighborsClassifier(n_neighbors=best_n_neighbors)

# Fit the best classifier to your training data
best_classifier.fit(X_train, y_train)

# Make predictions using the best classifier
y_pred = best_classifier.predict(X_test)

# Evaluate the accuracy of the best classifier
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Accuracy: 0.8360655737704918

In [215]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

# Define the parameter grid
param_grid = {'n_neighbors': range(1, 21)}

# Create a StratifiedKFold object for cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)  # Set random_state for reproducibility

# Create a GridSearchCV object with StratifiedKFold
grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=cv, scoring='accuracy')

# Fit the grid search to your training data
grid_search.fit(X_train, y_train)

# ... (rest of the code remains the same)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 21)}, scoring='accuracy')

In [216]:
# Example using cross_val_score with adjusted n_splits
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, X, y_discretized, cv=3)  # Using cv=3 instead of the default 5

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

Logistic Regression (for classification tasks)

In [218]:
%matplotlib inline

In [219]:
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline
import matplotlib.pyplot as plt

In [220]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [221]:
# Create a Logistic Regression object
model = LogisticRegression()

# Train the model using your training data
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [222]:
# Predict on the test data
y_pred = model.predict(X_test)

In [223]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate classification report
print(classification_report(y_test, y_pred))

# Generate confusion matrix
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9508196721311475
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        16
           1       0.95      0.97      0.96        37
           2       1.00      0.88      0.93         8

    accuracy                           0.95        61
   macro avg       0.96      0.93      0.94        61
weighted avg       0.95      0.95      0.95        61

[[15  1  0]
 [ 1 36  0]
 [ 0  1  7]]

In [224]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9508196721311475
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        16
           1       0.95      0.97      0.96        37
           2       1.00      0.88      0.93         8

    accuracy                           0.95        61
   macro avg       0.96      0.93      0.94        61
weighted avg       0.95      0.95      0.95        61

[[15  1  0]
 [ 1 36  0]
 [ 0  1  7]]

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Decision Trees

In [227]:
from sklearn.tree import DecisionTreeClassifier

# Create and train the Decision Tree model
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

# Make predictions using the Decision Tree model
tree_y_pred = tree_model.predict(X_test)

# You can now use 'tree_y_pred' for further analysis or actions

In [228]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, tree_y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [229]:
from sklearn.metrics import classification_report
print(classification_report(y_test, tree_y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        37
           2       1.00      1.00      1.00         8

    accuracy                           1.00        61
   macro avg       1.00      1.00      1.00        61
weighted avg       1.00      1.00      1.00        61

In [230]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, tree_y_pred))

[[16  0  0]
 [ 0 37  0]
 [ 0  0  8]]

Naive Bayes classifier to the mix and compare its performance with the Decision Tree

In [232]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create and train the Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Make predictions using the Naive Bayes model
nb_y_pred = nb_model.predict(X_test)

# Evaluate the Naive Bayes model
nb_accuracy = accuracy_score(y_test, nb_y_pred)
print("Naive Bayes Accuracy:", nb_accuracy)
print(classification_report(y_test, nb_y_pred))
print(confusion_matrix(y_test, nb_y_pred))

# Create and train the Decision Tree model
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

# Make predictions using the Decision Tree model
tree_y_pred = tree_model.predict(X_test)

# Evaluate the Decision Tree model
tree_accuracy = accuracy_score(y_test, tree_y_pred)
print("Decision Tree Accuracy:", tree_accuracy)
print(classification_report(y_test, tree_y_pred))
print(confusion_matrix(y_test, tree_y_pred))

Naive Bayes Accuracy: 0.9180327868852459
              precision    recall  f1-score   support

           0       0.93      0.88      0.90        16
           1       0.92      0.95      0.93        37
           2       0.88      0.88      0.88         8

    accuracy                           0.92        61
   macro avg       0.91      0.90      0.90        61
weighted avg       0.92      0.92      0.92        61

[[14  2  0]
 [ 1 35  1]
 [ 0  1  7]]
Decision Tree Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        37
           2       1.00      1.00      1.00         8

    accuracy                           1.00        61
   macro avg       1.00      1.00      1.00        61
weighted avg       1.00      1.00      1.00        61

[[16  0  0]
 [ 0 37  0]
 [ 0  0  8]]